/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Model.Car;
import Model.ServiceRecords;
import java.util.ArrayList;

/**
 *
 * @author 85251
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    ServiceRecords records;
    ArrayList<Car> predefinedRecords;
    
    public MainJFrame() {
        initComponents();
        records = new ServiceRecords();
        this.predefinedRecords = predefinedRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        workArea = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 750));

        workArea.setPreferredSize(new java.awt.Dimension(1000, 627));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        controlPanel.setPreferredSize(new java.awt.Dimension(129, 627));

        btnCreate.setText("Create car");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View Cars");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnCreate)
                .addGap(35, 35, 35)
                .addComponent(btnView)
                .addGap(31, 31, 31)
                .addComponent(btnSearch)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<Car> predefinedRecords(){
        ArrayList<Car> predefined = new ArrayList<Car>();
        Car car1 = new Car();
        car1.setId("1A");
        car1.setBrand("BMW");
        car1.setCity("Malden");
        car1.setModel("X2");
        car1.setYear(2020);
        car1.setSeatsNumber(4);
        car1.setCertificate(true);
        car1.setAvailability(false);
        predefined.add(car1);
        
        Car car2 = new Car();
        car2.setId("1B");
        car2.setBrand("BMW");
        car2.setCity("Fenway");
        car2.setModel("X3");
        car2.setYear(2019);
        car2.setSeatsNumber(4);
        car2.setCertificate(true);
        car2.setAvailability(true);
        predefined.add(car2);
        
        Car car3 = new Car();
        car3.setId("1C");
        car3.setBrand("BMW");
        car3.setCity("Silicon Valley");
        car3.setModel("X4");
        car3.setYear(2021);
        car3.setSeatsNumber(5);
        car3.setCertificate(true);
        car3.setAvailability(false);
        predefined.add(car3);
        
        Car car4 = new Car();
        car4.setId("1D");
        car4.setBrand("BMW");
        car4.setCity("Seattle");
        car4.setModel("X3");
        car4.setYear(2016);
        car4.setSeatsNumber(4);
        car4.setCertificate(true);
        car4.setAvailability(true);
        predefined.add(car4);
        
        Car car5 = new Car();
        car5.setId("2A");
        car5.setBrand("Benz");
        car5.setCity("Malden");
        car5.setModel("C6");
        car5.setYear(2017);
        car5.setSeatsNumber(5);
        car5.setCertificate(true);
        car5.setAvailability(true);
        predefined.add(car5);
        
        Car car6 = new Car();
        car6.setId("2B");
        car6.setBrand("Benz");
        car6.setCity("Fenway");
        car6.setModel("C4");
        car6.setYear(2019);
        car6.setSeatsNumber(6);
        car6.setCertificate(false);
        car6.setAvailability(false);
        predefined.add(car6);
        
        Car car7 = new Car();
        car7.setId("2C");
        car7.setBrand("Benz");
        car7.setCity("Silicon Valley");
        car7.setModel("C6");
        car7.setYear(2018);
        car7.setSeatsNumber(6);
        car7.setCertificate(true);
        car7.setAvailability(false);
        predefined.add(car7);
        
        Car car8 = new Car();
        car8.setId("2D");
        car8.setBrand("Benz");
        car8.setCity("Seattle");
        car8.setModel("C5");
        car8.setYear(2017);
        car8.setSeatsNumber(7);
        car8.setCertificate(false);
        car8.setAvailability(false);
        predefined.add(car8);
        
        Car car9 = new Car();
        car9.setId("3A");
        car9.setBrand("GW");
        car9.setCity("Malden");
        car9.setModel("S3");
        car9.setYear(2019);
        car9.setSeatsNumber(2);
        car9.setCertificate(true);
        car9.setAvailability(false);
        predefined.add(car9);

        
        Car car10 = new Car();
        car10.setId("3B");
        car10.setBrand("GW");
        car10.setCity("Fenway");
        car10.setModel("S3");
        car10.setYear(2019);
        car10.setSeatsNumber(2);
        car10.setCertificate(false);
        car10.setAvailability(true);
        predefined.add(car10);
        
        Car car11 = new Car();
        car11.setId("3C");
        car11.setBrand("GW");
        car11.setCity("Silicon Valley");
        car11.setModel("S5");
        car11.setYear(2021);
        car11.setSeatsNumber(5);
        car11.setCertificate(false);
        car11.setAvailability(true);
        predefined.add(car11);
        
        Car car12 = new Car();
        car12.setId("3D");
        car12.setBrand("GW");
        car12.setCity("Seattle");
        car12.setModel("S4");
        car12.setYear(2020);
        car12.setSeatsNumber(5);
        car12.setCertificate(true);
        car12.setAvailability(true);
        predefined.add(car12);
        
        Car car13 = new Car();
        car13.setId("4A");
        car13.setBrand("Aodi");
        car13.setCity("Malden");
        car13.setModel("A2");
        car13.setYear(2021);
        car13.setSeatsNumber(7);
        car13.setCertificate(false);
        car13.setAvailability(true);
        predefined.add(car13);
        
        Car car14 = new Car();
        car14.setId("4B");
        car14.setBrand("Aodi");
        car14.setCity("Fenway");
        car14.setModel("A8");
        car14.setYear(2020);
        car14.setSeatsNumber(7);
        car14.setCertificate(true);
        car14.setAvailability(false);
        predefined.add(car14);
        
        Car car15 = new Car();
        car15.setId("4C");
        car15.setBrand("Aodi");
        car15.setCity("Silicon Valley");
        car15.setModel("A2");
        car15.setYear(2018);
        car15.setSeatsNumber(7);
        car15.setCertificate(false);
        car15.setAvailability(false);
        predefined.add(car15);
        
        Car car16 = new Car();
        car16.setId("4D");
        car16.setBrand("Aodi");
        car16.setCity("Seattle");
        car16.setModel("A3");
        car16.setYear(2021);
        car16.setSeatsNumber(5);
        car16.setCertificate(true);
        car16.setAvailability(false);
        predefined.add(car16);
        return predefined;
    }
    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateJPanel createPanel = new CreateJPanel(records);
        splitPane.setRightComponent(createPanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewPanel;
        if(records.getRecords().size()==0)
            records.setRecords(predefinedRecords);
        viewPanel = new ViewJPanel(records);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        SearchJPanel searchpanel = new SearchJPanel(records);
        splitPane.setRightComponent(searchpanel);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
